### ISSUE TITLE
Error: The `libsass` binding was not found

### ISSUE THREAD

**Issue by aamnah** [mechio/takana#106]
```
node -v: v7.7.2
npm -v: 4.1.2
which node: /usr/local/bin/node
which npm: /usr/local/bin/npm
node -p process.arch: x64
node -p process.platform: darwin
OS: macOS Sierra, v10.12.3
```
It says that `libsass` binding was not found and it might be a Node version issue.
I have ran `npm rebuild node-sass` twice, but it keeps giving the error.

Here's the full error

```
~/Projects/mysite.com $ takana .
/usr/local/lib/node_modules/takana/node_modules/node-sass/lib/extensions.js:158
    throw new Error([
    ^

Error: The `libsass` binding was not found in /usr/local/lib/node_modules/takana/node_modules/node-sass/vendor/darwin-x64-51/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
    at Object.sass.getBinaryPath (/usr/local/lib/node_modules/takana/node_modules/node-sass/lib/extensions.js:158:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/takana/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (/usr/local/lib/node_modules/takana/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/takana/lib/renderer/scss.coffee:4:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/takana/lib/renderer/scss.coffee:72:4)
    at Module._compile (module.js:571:32)
    at Object.loadFile (/usr/local/lib/node_modules/takana/node_modules/coffee-script/lib/coffee-script/coffee-script.js:182:19)
    at Module.load (/usr/local/lib/node_modules/takana/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/takana/lib/renderer/index.coffee:6:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/takana/lib/renderer/index.coffee:33:4)
    at Module._compile (module.js:571:32)
    at Object.loadFile (/usr/local/lib/node_modules/takana/node_modules/coffee-script/lib/coffee-script/coffee-script.js:182:19)
    at Module.load (/usr/local/lib/node_modules/takana/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/takana/lib/server.coffee:6:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/takana/lib/server.coffee:195:4)
    at Module._compile (module.js:571:32)
    at Object.loadFile (/usr/local/lib/node_modules/takana/node_modules/coffee-script/lib/coffee-script/coffee-script.js:182:19)
    at Module.load (/usr/local/lib/node_modules/takana/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/takana/index.js:11:33)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (/usr/local/lib/node_modules/takana/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/takana/bin/takana:13:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3
```

I also tried deleting the `node-sass` folder inside `node_modules` and running `npm install` again and got 

```
Cannot download "https://github.com/sass/node-sass/releases/download/v3.4.2/darwin-x64-51_binding.node":

HTTP error 404 Not Found
```

Ideas? How do i get it to work?

**Comment by aamnah** [comment]
Okay, i deleted the node-sass@3.4.2 dependency from `package.json` and installed node-sass with `npm i -S node-sass`. It installed `node-sass@4.5.1` and it seems to be working now..
