### ISSUE TITLE
scratch directory is empty

### ISSUE THREAD

**Issue by dprovost1990** [mechio/takana#71]
[14:07:46] [INFO] - buffer updated for /home/sites/far-west/css/main.css
cp: copyFileSync: could not write to dest file (code=ENOENT):/home/.takana/scratch//css/main.css

cp: copyFileSync: could not write to dest file (code=ENOENT):/home/.takana/scratch//css/main.css

when i check the scratch directory, it is empty....there is no css folder.

If I make a css folder, takana creates a css file.  But it never gets updated, it stays blank.

**Comment by dprovost1990** [comment]
switched python > python2.7 to python > python3
and it works

Which is wierd, because you can't install with python3, you have to ln -sf to python2...but takana only works for me when i syslink back to python3

**Comment by dprovost1990** [comment]
Ok I don't think it had anything to with python.  I got it to work by storing all my css files in the directory I ran takana on.

But I keep all my css usually in a folder called css

Then takana cant render the files.

But if I go into the scratch folder and make a directory called css, it then will make my main.css file inside the folder.

**Comment by dprovost1990** [comment]
Back to my original problem.  In Takana 0.4.3, the scratch directory does not write to the css files.  I have to manually create the directories either way...but for some reason, in V 0.4.3 the output css files are blank.  It was working ok in 0.4.2, but now I'm getting a new error when I try to connect my browser:
fs.js:1172
    throw errnoException(err, 'watch');
          ^
Error: watch ENOSPC
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (fs.js:1172:11)
    at Object.fs.watch (fs.js:1198:11)
    at EventEmitter.FSWatcher._watch (/usr/lib/node_modules/takana/node_modules/chokidar/index.js:253:18)
    at EventEmitter.FSWatcher._handleFile (/usr/lib/node_modules/takana/node_modules/chokidar/index.js:308:8)
    at /usr/lib/node_modules/takana/node_modules/chokidar/index.js:384:62
    at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by dprovost1990** [comment]
All the issues seemed to be revolving around permissions.  I've installed 4.3, and got it working by chmod 777 on scratch directory.
