### ISSUE TITLE
takana crashing on browser refresh

### ISSUE THREAD

**Issue by dprovost1990** [mechio/takana#72]
Hello,

When I run takana on my sites directory, everything looks good, until I hit refresh on my browser.   Then I get the following error and I'm pushed back out to the command line.

fs.js:1172
    throw errnoException(err, 'watch');
          ^
Error: watch ENOSPC
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (fs.js:1172:11)
    at Object.fs.watch (fs.js:1198:11)
    at EventEmitter.FSWatcher._watch (/usr/lib/node_modules/takana/node_modules/chokidar/index.js:253:18)
    at EventEmitter.FSWatcher._handleFile (/usr/lib/node_modules/takana/node_modules/chokidar/index.js:308:8)
    at /usr/lib/node_modules/takana/node_modules/chokidar/index.js:384:62
    at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by dprovost1990** [comment]
Still crashing

[08:44:55] [INFO] - rendered /mnt/htdocs/htdocs/big-street/css/main.css
fs.js:1172
    throw errnoException(err, 'watch');
          ^
Error: watch ENOSPC
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (fs.js:1172:11)
    at Object.fs.watch (fs.js:1198:11)
    at EventEmitter.FSWatcher._watch (/usr/lib/node_modules/takana/node_modules/chokidar/index.js:253:18)
    at EventEmitter.FSWatcher._handleFile (/usr/lib/node_modules/takana/node_modules/chokidar/index.js:3

**Comment by dprovost1990** [comment]
I upgraded to 4.3, and made sure to run takana on site root instead of my project folder root (many many websites).
