### ISSUE TITLE
Cannot install, ELIFECYCLE error, node-sass@1.0.3 install: `node build.js`

### ISSUE THREAD

**Issue by blisst** [mechio/takana#77]
Hello, I am unable to install takana on Windows
node: 0.12.2
npm: 2.11.1
node-gyp: 2.0.1
I'm running the command as an administrator.

```
Error: node-sass@1.0.3 install: `node build.js`
Exit status 1
at EventEmitter.<anonymous> (C:\Users\Hal\AppData\Roaming\nvm\v0.12.2\node_modules\npm\lib\utils\lifecycle.js:213:16)
at EventEmitter.emit (events.js:110:17)
at ChildProcess.<anonymous> (C:\Users\Hal\AppData\Roaming\nvm\v0.12.2\node_modules\npm\lib\utils\spawn.js:24:14)
at ChildProcess.emit (events.js:110:17)
at maybeClose (child_process.js:1015:16)
at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
pkgid node-sass@1.0.3
cwd C:\CODING\npm
error Windows_NT 6.1.7601
error argv "c:\\Program Files (x86)\\nodejs\\node.exe" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "takana"
error node v0.12.2
error npm  v2.11.1
error code ELIFECYCLE
error node-sass@1.0.3 install: `node build.js`
error Exit status 1
error Failed at the node-sass@1.0.3 install script 'node build.js'.
error This is most likely a problem with the node-sass package,
error not with npm itself.
```

I looked around on node-sass repo on most issues were solved by updating node-sass.  Is this an option for takana?
Any help would be much appreciated!

**Comment by Macro-T** [comment]
I'm having the same problem. I tried making my own branch, and updating node-sass dependency to `~3.2.0`. He settled smoothly, but when I run the `Takana` command to watch live my sass I got nothing, simply do nothing. Any ideas?

**Comment by billybrown** [comment]
+1

I tried the same thing as taverasmisael (making my own branch and updating the node-sass dependency). Didn't work. Would love for this to get updated along with node-sass/libsass/etc. 

FWIW I have it working on my machine with node version 0.12.7 (which I set using [nvm](https://github.com/creationix/nvm))

Great tool by the way! On-keystroke css compilation is a must have for me for designing things in browser.

**Comment by rasj** [comment]
I submit a new pull request where i fix takana to work with node-sass 3.3.3
https://github.com/mechio/takana/pull/89

**Comment by taverasmisael** [comment]
+1

Thanks @rasj :+1:
