### ISSUE TITLE
List Dependencies

### ISSUE THREAD

**Issue by danieldogeanu** [mechio/takana#91]
Hi! I've been trying to install takana on 5 different computers with no avail. All failing for different reasons and running different versions of Windows (7, 8 and 10).

I believe this happens because this plugin has dependencies that are not listed anywhere. Please list all the dependencies needed for it. Starting with python and ending with whatever it requires to work without any problems.

Please notify me when you update the dependencies list, so I can further test it. Thanks.

**Comment by danieldogeanu** [comment]
Oh and this is what I get when I try to install it on my PC:
```
npm WARN optional dep failed, continuing fsevents@1.0.5

> websocket@1.0.22 install C:\Users\danie\AppData\Roaming\npm\node_modules\takana\node_modules\websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)


C:\Users\danie\AppData\Roaming\npm\node_modules\takana\node_modules\websocket>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
|
> node-sass@1.0.3 install C:\Users\danie\AppData\Roaming\npm\node_modules\takana\node_modules\node-sass
> node build.js

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.

C:\Users\danie\AppData\Roaming\npm\node_modules\takana\node_modules\node-sass>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\danie\AppData\Roaming\npm\node_modules\takana\node_modules\node-sass
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
Build failed
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "takana"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.0.3 install: `node build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@1.0.3 install script 'node build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\danie\npm-debug.log
```

**Comment by danieldogeanu** [comment]
And I've also attached the npm-debug.log.
[npm-debug.zip](https://github.com/mechio/takana/files/52916/npm-debug.zip)
